<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="calculator-11549842764j1xauc4kti-removebg-preview.png" />
    <None Remove="img\calculator-11549842764j1xauc4kti-removebg-preview.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="calculator-11549842764j1xauc4kti-removebg-preview.png" />
    <Resource Include="img\calculator-11549842764j1xauc4kti-removebg-preview.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
